apiVersion: v1
kind: Service
metadata:
  name: hello-world
spec:
  selector:
    app: go-hello # Match this label with your pod's labels
  ports:
    - protocol: TCP
      port: 8080  # Port on the service
      targetPort: 8080  # Port on the pod
  type: NodePort